# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd3a31c08e877ff2a1739c4ea65a338212ee1cccb558bcf881beaee05adb027c5dec3e81b234c4d828a7dca6c616c867e4bdfeb6e332ffb4b9c3d3a8446ddae8

test:
  secret_key_base: 79aea4200a400b994f1f05d468bebe5adda0c2cb24b9bb046b197f3881467c3a0283e364c941140b97c6fd5c5c4440287195b71bcd8e26c19c2611bc11567c57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
